#!/usr/bin/env ruby
require File.expand_path(File.join(File.dirname(__FILE__), '..', 'vendor', 'gems', 'environment'))
Bundler.require_env

libs =  " -r irb/completion"

exec "irb #{libs} --simple-prompt"
